#!/bin/bash
# Quick reference for testing Axiom Terminal with real data providers

echo "🚀 AXIOM TERMINAL - API SETUP COMPLETE"
echo "========================================="
echo ""
echo "✓ .env file configured with API keys:"
echo "  - Alpha Vantage    ✓"
echo "  - FRED             ✓"
echo "  - Fin Hub          ✓"
echo "  - News API         ✓"
echo "  - Groq LLM         ✓"
echo ""
echo "Next steps:"
echo ""
echo "1. Install dependencies (if in development):"
echo "   pip install -r backend/requirements.txt"
echo ""
echo "2. Start the backend server:"
echo "   cd /Users/adityapareek/BlackGrid"
echo "   python3 -m uvicorn backend.app.main:app --reload --port 8000"
echo ""
echo "3. In another terminal, test endpoints:"
echo "   # Real market data"
echo "   curl http://localhost:8000/api/market/overview"
echo ""
echo "   # Real company details"
echo "   curl http://localhost:8000/api/asset/AAPL"
echo ""
echo "   # Real technical data (30 daily candles)"
echo "   curl http://localhost:8000/api/asset/AAPL/technicals?days=30"
echo ""
echo "   # AI analyst report using Groq LLM"
echo "   curl http://localhost:8000/api/report/AAPL"
echo ""
echo "   # ML forecast with 4 models"
echo "   curl http://localhost:8000/api/asset/AAPL/forecast?days=30"
echo ""
echo "4. Start frontend (in another terminal):"
echo "   cd /Users/adityapareek/BlackGrid/frontend"
echo "   npm install  # if needed"
echo "   npm run dev"
echo ""
echo "5. Open browser:"
echo "   Frontend: http://localhost:3000"
echo "   API Docs: http://localhost:8000/docs"
echo "   OpenAPI:  http://localhost:8000/openapi.json"
echo ""
echo "========================================="
echo "Documentation:"
echo "  - API_SETUP_GUIDE.md  → Full setup & security guide"
echo "  - QUICKSTART.md       → Code examples"
echo "  - TESTING.md          → Endpoint testing guide"
echo "========================================="
