"""
Indicator catalog — 100 indicator/condition primitives for the BlackGrid strategy engine.

Each entry maps an indicator key to its metadata:
    display_name, category, parameters, description, supported_operators,
    required_fields, output_type.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Shared operator lists
# ---------------------------------------------------------------------------
_NUMERIC_OPS = ["crosses_above", "crosses_below", "gt", "lt", "gte", "lte", "eq", "between"]
_BOOL_OPS = ["eq"]

# ---------------------------------------------------------------------------
# INDICATOR_CATALOG  –  100 entries, grouped by category
# ---------------------------------------------------------------------------

INDICATOR_CATALOG: dict[str, dict] = {

    # ===== TREND (1-10) ====================================================

    "sma": {
        "display_name": "Simple Moving Average",
        "category": "Trend",
        "parameters": {"period": 20},
        "description": "Arithmetic mean of close over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "ema": {
        "display_name": "Exponential Moving Average",
        "category": "Trend",
        "parameters": {"period": 20},
        "description": "Exponentially weighted moving average of close.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "wma": {
        "display_name": "Weighted Moving Average",
        "category": "Trend",
        "parameters": {"period": 20},
        "description": "Linearly weighted moving average giving more weight to recent bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "hma": {
        "display_name": "Hull Moving Average",
        "category": "Trend",
        "parameters": {"period": 20},
        "description": "Hull MA — reduces lag by combining WMAs of different lengths.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "dema": {
        "display_name": "Double Exponential Moving Average",
        "category": "Trend",
        "parameters": {"period": 20},
        "description": "2×EMA(period) − EMA(EMA(period)), less lag than standard EMA.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "tema": {
        "display_name": "Triple Exponential Moving Average",
        "category": "Trend",
        "parameters": {"period": 20},
        "description": "Triple EMA indicator (Mulloy); further lag reduction over DEMA.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "vwma": {
        "display_name": "Volume Weighted Moving Average",
        "category": "Trend",
        "parameters": {"period": 20},
        "description": "Moving average weighted by volume; heavier-volume bars count more.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close", "volume"],
        "output_type": "line",
    },
    "rma": {
        "display_name": "Running / Wilder's Moving Average",
        "category": "Trend",
        "parameters": {"period": 14},
        "description": "Wilder's smoothing method (alpha = 1/period).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "alma": {
        "display_name": "Arnaud Legoux Moving Average",
        "category": "Trend",
        "parameters": {"period": 20, "offset_pct": 0.85, "sigma": 6.0},
        "description": "Gaussian-weighted moving average with adjustable offset and sigma.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "kama": {
        "display_name": "Kaufman Adaptive Moving Average",
        "category": "Trend",
        "parameters": {"period": 10, "fast_period": 2, "slow_period": 30},
        "description": "Adaptive MA that speeds up in trends and slows in chop.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },

    # ===== MOMENTUM (11-20) ================================================

    "rsi": {
        "display_name": "Relative Strength Index",
        "category": "Momentum",
        "parameters": {"period": 14},
        "description": "Wilder's RSI — oscillates 0-100 measuring up/down momentum.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "stoch_k": {
        "display_name": "Stochastic %K",
        "category": "Momentum",
        "parameters": {"k_period": 14, "d_period": 3},
        "description": "Stochastic %K line showing where close sits in the recent range.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "stoch_d": {
        "display_name": "Stochastic %D",
        "category": "Momentum",
        "parameters": {"k_period": 14, "d_period": 3},
        "description": "Smoothed stochastic %D (SMA of %K).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "stoch_rsi": {
        "display_name": "Stochastic RSI",
        "category": "Momentum",
        "parameters": {"rsi_period": 14, "stoch_period": 14, "smooth_k": 3},
        "description": "Stochastic oscillator applied to RSI values.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "cci": {
        "display_name": "Commodity Channel Index",
        "category": "Momentum",
        "parameters": {"period": 20},
        "description": "Measures deviation of typical price from its SMA relative to MAD.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "williams_r": {
        "display_name": "Williams %R",
        "category": "Momentum",
        "parameters": {"period": 14},
        "description": "Williams %R — inverted stochastic oscillator (−100 to 0).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "roc": {
        "display_name": "Rate of Change",
        "category": "Momentum",
        "parameters": {"period": 12},
        "description": "Percentage change of close over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "momentum": {
        "display_name": "Price Momentum",
        "category": "Momentum",
        "parameters": {"period": 10},
        "description": "Ratio of current close to close *period* bars ago.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "tsi": {
        "display_name": "True Strength Index",
        "category": "Momentum",
        "parameters": {"long_period": 25, "short_period": 13},
        "description": "Double-smoothed momentum oscillator (−100 to 100).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "ultimate_osc": {
        "display_name": "Ultimate Oscillator",
        "category": "Momentum",
        "parameters": {"period1": 7, "period2": 14, "period3": 28},
        "description": "Combines three timeframes of buying pressure into one oscillator.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },

    # ===== OSCILLATOR (21-30) ==============================================

    "macd_line": {
        "display_name": "MACD Line",
        "category": "Oscillator",
        "parameters": {"fast": 12, "slow": 26, "signal_period": 9},
        "description": "MACD line (fast EMA − slow EMA).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "macd_signal": {
        "display_name": "MACD Signal Line",
        "category": "Oscillator",
        "parameters": {"fast": 12, "slow": 26, "signal_period": 9},
        "description": "Signal line (EMA of MACD line).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "macd_histogram": {
        "display_name": "MACD Histogram",
        "category": "Oscillator",
        "parameters": {"fast": 12, "slow": 26, "signal_period": 9},
        "description": "MACD histogram (MACD line − signal line).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "histogram",
    },
    "ppo": {
        "display_name": "Percentage Price Oscillator",
        "category": "Oscillator",
        "parameters": {"fast": 12, "slow": 26, "signal_period": 9},
        "description": "MACD expressed as a percentage of the slow EMA.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "trix": {
        "display_name": "TRIX",
        "category": "Oscillator",
        "parameters": {"period": 15},
        "description": "Rate of change of triple-smoothed EMA — filters noise.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "ao": {
        "display_name": "Awesome Oscillator",
        "category": "Oscillator",
        "parameters": {"fast": 5, "slow": 34},
        "description": "SMA(5) − SMA(34) of median price.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low"],
        "output_type": "histogram",
    },
    "ac": {
        "display_name": "Acceleration/Deceleration Oscillator",
        "category": "Oscillator",
        "parameters": {"fast": 5, "slow": 34, "smooth": 5},
        "description": "AO minus SMA(AO) — measures acceleration of momentum.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low"],
        "output_type": "histogram",
    },
    "fisher_transform": {
        "display_name": "Fisher Transform",
        "category": "Oscillator",
        "parameters": {"period": 10},
        "description": "Normalises prices into a Gaussian distribution for sharper signals.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low"],
        "output_type": "line",
    },
    "coppock": {
        "display_name": "Coppock Curve",
        "category": "Oscillator",
        "parameters": {"wma_period": 10, "roc_long": 14, "roc_short": 11},
        "description": "WMA of the sum of two rates of change — long-term momentum.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "detrended_price": {
        "display_name": "Detrended Price Oscillator",
        "category": "Oscillator",
        "parameters": {"period": 20},
        "description": "Close minus SMA shifted back by half the period — removes trend.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },

    # ===== VOLATILITY (31-40) ==============================================

    "bbands_upper": {
        "display_name": "Bollinger Upper Band",
        "category": "Volatility",
        "parameters": {"period": 20, "std_dev": 2.0},
        "description": "SMA + std_dev × standard deviation.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "band",
    },
    "bbands_lower": {
        "display_name": "Bollinger Lower Band",
        "category": "Volatility",
        "parameters": {"period": 20, "std_dev": 2.0},
        "description": "SMA − std_dev × standard deviation.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "band",
    },
    "bbands_middle": {
        "display_name": "Bollinger Middle Band",
        "category": "Volatility",
        "parameters": {"period": 20, "std_dev": 2.0},
        "description": "Simple moving average (middle Bollinger line).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "bbands_width": {
        "display_name": "Bollinger Band Width",
        "category": "Volatility",
        "parameters": {"period": 20, "std_dev": 2.0},
        "description": "(Upper − Lower) / Middle — normalised band width.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "bbands_pctb": {
        "display_name": "Bollinger %B",
        "category": "Volatility",
        "parameters": {"period": 20, "std_dev": 2.0},
        "description": "(Close − Lower) / (Upper − Lower) — position within bands.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "keltner_upper": {
        "display_name": "Keltner Channel Upper",
        "category": "Volatility",
        "parameters": {"ema_period": 20, "atr_period": 14, "multiplier": 2.0},
        "description": "EMA + multiplier × ATR.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "band",
    },
    "keltner_lower": {
        "display_name": "Keltner Channel Lower",
        "category": "Volatility",
        "parameters": {"ema_period": 20, "atr_period": 14, "multiplier": 2.0},
        "description": "EMA − multiplier × ATR.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "band",
    },
    "atr": {
        "display_name": "Average True Range",
        "category": "Volatility",
        "parameters": {"period": 14},
        "description": "Wilder-smoothed average true range.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "natr": {
        "display_name": "Normalized ATR",
        "category": "Volatility",
        "parameters": {"period": 14},
        "description": "ATR / close × 100 — percentage-based volatility.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "historical_vol": {
        "display_name": "Historical Volatility",
        "category": "Volatility",
        "parameters": {"period": 20},
        "description": "Annualised standard deviation of log returns.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },

    # ===== VOLUME (41-50) ==================================================

    "obv": {
        "display_name": "On Balance Volume",
        "category": "Volume",
        "parameters": {},
        "description": "Cumulative volume added on up bars, subtracted on down bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close", "volume"],
        "output_type": "line",
    },
    "cmf": {
        "display_name": "Chaikin Money Flow",
        "category": "Volume",
        "parameters": {"period": 20},
        "description": "Sum(CLV × volume) / Sum(volume) over period — buying/selling pressure.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close", "volume"],
        "output_type": "line",
    },
    "mfi": {
        "display_name": "Money Flow Index",
        "category": "Volume",
        "parameters": {"period": 14},
        "description": "Volume-weighted RSI (0-100).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close", "volume"],
        "output_type": "line",
    },
    "vwap": {
        "display_name": "Session VWAP",
        "category": "Volume",
        "parameters": {"period": 20},
        "description": "Rolling VWAP approximation over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close", "volume"],
        "output_type": "line",
    },
    "ad_line": {
        "display_name": "Accumulation/Distribution Line",
        "category": "Volume",
        "parameters": {},
        "description": "Cumulative CLV × volume — tracks money flow into/out of an asset.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close", "volume"],
        "output_type": "line",
    },
    "eom": {
        "display_name": "Ease of Movement",
        "category": "Volume",
        "parameters": {"period": 14},
        "description": "Relates price movement to volume — higher values mean easier movement.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "volume"],
        "output_type": "line",
    },
    "volume_sma": {
        "display_name": "Volume SMA",
        "category": "Volume",
        "parameters": {"period": 20},
        "description": "Simple moving average of volume.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["volume"],
        "output_type": "line",
    },
    "volume_ratio": {
        "display_name": "Volume Ratio",
        "category": "Volume",
        "parameters": {"period": 20},
        "description": "Current volume / SMA(volume) — spike detection ratio.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["volume"],
        "output_type": "line",
    },
    "pvt": {
        "display_name": "Price Volume Trend",
        "category": "Volume",
        "parameters": {},
        "description": "Cumulative (pct_change × volume) — combines price and volume trends.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close", "volume"],
        "output_type": "line",
    },
    "nvi": {
        "display_name": "Negative Volume Index",
        "category": "Volume",
        "parameters": {},
        "description": "Tracks cumulative returns on days when volume decreases.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close", "volume"],
        "output_type": "line",
    },

    # ===== MARKET STRUCTURE (51-60) ========================================

    "donchian_upper": {
        "display_name": "Donchian Channel Upper",
        "category": "Market Structure",
        "parameters": {"period": 20},
        "description": "Highest high over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high"],
        "output_type": "band",
    },
    "donchian_lower": {
        "display_name": "Donchian Channel Lower",
        "category": "Market Structure",
        "parameters": {"period": 20},
        "description": "Lowest low over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["low"],
        "output_type": "band",
    },
    "rolling_high": {
        "display_name": "Rolling N-bar High",
        "category": "Market Structure",
        "parameters": {"period": 20},
        "description": "Highest close over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "rolling_low": {
        "display_name": "Rolling N-bar Low",
        "category": "Market Structure",
        "parameters": {"period": 20},
        "description": "Lowest close over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "higher_high": {
        "display_name": "Higher High Detection",
        "category": "Market Structure",
        "parameters": {"period": 5},
        "description": "True when current high exceeds the highest high of the previous *period* bars.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["high"],
        "output_type": "boolean",
    },
    "lower_low": {
        "display_name": "Lower Low Detection",
        "category": "Market Structure",
        "parameters": {"period": 5},
        "description": "True when current low is below the lowest low of the previous *period* bars.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["low"],
        "output_type": "boolean",
    },
    "breakout_up": {
        "display_name": "Upward Breakout",
        "category": "Market Structure",
        "parameters": {"period": 20},
        "description": "True when close exceeds the *period*-bar rolling high.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["high", "close"],
        "output_type": "boolean",
    },
    "breakout_down": {
        "display_name": "Downward Breakout",
        "category": "Market Structure",
        "parameters": {"period": 20},
        "description": "True when close drops below the *period*-bar rolling low.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["low", "close"],
        "output_type": "boolean",
    },
    "pivot_high": {
        "display_name": "Pivot High",
        "category": "Market Structure",
        "parameters": {"left": 5, "right": 5},
        "description": "True at bars where high is higher than *left* preceding and *right* following bars.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["high"],
        "output_type": "boolean",
    },
    "pivot_low": {
        "display_name": "Pivot Low",
        "category": "Market Structure",
        "parameters": {"left": 5, "right": 5},
        "description": "True at bars where low is lower than *left* preceding and *right* following bars.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["low"],
        "output_type": "boolean",
    },

    # ===== MEAN REVERSION (61-70) ==========================================

    "zscore": {
        "display_name": "Z-Score",
        "category": "Mean Reversion",
        "parameters": {"period": 20},
        "description": "(Close − SMA) / StdDev over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "pct_from_sma": {
        "display_name": "Percent from SMA",
        "category": "Mean Reversion",
        "parameters": {"period": 20},
        "description": "(Close − SMA) / SMA × 100.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "pct_from_ema": {
        "display_name": "Percent from EMA",
        "category": "Mean Reversion",
        "parameters": {"period": 20},
        "description": "(Close − EMA) / EMA × 100.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "mean_rev_signal": {
        "display_name": "Mean Reversion Signal",
        "category": "Mean Reversion",
        "parameters": {"period": 20, "entry_z": -2.0, "exit_z": 0.0},
        "description": "Z-score-based mean reversion entry signal (boolean when z < entry_z).",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["close"],
        "output_type": "boolean",
    },
    "rsi_divergence": {
        "display_name": "RSI Divergence",
        "category": "Mean Reversion",
        "parameters": {"rsi_period": 14, "lookback": 10},
        "description": "Simplified divergence: price falls while RSI rises (bullish) or vice-versa.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "price_channel_position": {
        "display_name": "Price Channel Position",
        "category": "Mean Reversion",
        "parameters": {"period": 20},
        "description": "(Close − rolling_low) / (rolling_high − rolling_low); 0–1 range position.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "bb_position": {
        "display_name": "Bollinger Band Position",
        "category": "Mean Reversion",
        "parameters": {"period": 20, "std_dev": 2.0},
        "description": "Same as %B — close's position within Bollinger Bands (0 = lower, 1 = upper).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "keltner_position": {
        "display_name": "Keltner Channel Position",
        "category": "Mean Reversion",
        "parameters": {"ema_period": 20, "atr_period": 14, "multiplier": 2.0},
        "description": "(Close − lower) / (upper − lower) within Keltner Channel.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "stdev_channel_upper": {
        "display_name": "Std Dev Channel Upper",
        "category": "Mean Reversion",
        "parameters": {"period": 20, "multiplier": 2.0},
        "description": "SMA + multiplier × rolling standard deviation of close.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "band",
    },
    "stdev_channel_lower": {
        "display_name": "Std Dev Channel Lower",
        "category": "Mean Reversion",
        "parameters": {"period": 20, "multiplier": 2.0},
        "description": "SMA − multiplier × rolling standard deviation of close.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "band",
    },

    # ===== BREADTH / RELATIVE (71-80) ======================================

    "relative_strength": {
        "display_name": "Relative Strength vs Benchmark",
        "category": "Breadth",
        "parameters": {"period": 20},
        "description": "Rolling ratio of asset return to benchmark return (requires benchmark column or defaults to 1).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "return_over_n": {
        "display_name": "N-bar Return",
        "category": "Breadth",
        "parameters": {"period": 20},
        "description": "Percentage return over *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "gap_pct": {
        "display_name": "Gap Percentage",
        "category": "Breadth",
        "parameters": {},
        "description": "(Open − previous Close) / previous Close × 100.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["open", "close"],
        "output_type": "line",
    },
    "true_range": {
        "display_name": "True Range",
        "category": "Breadth",
        "parameters": {},
        "description": "Single-bar true range: max(H-L, |H-prevC|, |L-prevC|).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "avg_true_range_pct": {
        "display_name": "ATR Percentage",
        "category": "Breadth",
        "parameters": {"period": 14},
        "description": "ATR / close × 100 — same as NATR, provided as breadth metric.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "up_down_ratio": {
        "display_name": "Up/Down Ratio",
        "category": "Breadth",
        "parameters": {"period": 20},
        "description": "Count of up bars / count of down bars over *period*.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "positive_bars_pct": {
        "display_name": "Positive Bars %",
        "category": "Breadth",
        "parameters": {"period": 20},
        "description": "Percentage of bars with positive close change over *period*.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "consecutive_up": {
        "display_name": "Consecutive Up Bars",
        "category": "Breadth",
        "parameters": {},
        "description": "Running count of consecutive bars where close > previous close.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "value",
    },
    "consecutive_down": {
        "display_name": "Consecutive Down Bars",
        "category": "Breadth",
        "parameters": {},
        "description": "Running count of consecutive bars where close < previous close.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "value",
    },
    "bar_range_pct": {
        "display_name": "Bar Range %",
        "category": "Breadth",
        "parameters": {},
        "description": "(High − Low) / Close × 100.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },

    # ===== BASELINE (81-90) ================================================

    "supertrend": {
        "display_name": "SuperTrend",
        "category": "Baseline",
        "parameters": {"period": 10, "multiplier": 3.0},
        "description": "ATR-based trend-following line that flips direction on breakouts.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "supertrend_direction": {
        "display_name": "SuperTrend Direction",
        "category": "Baseline",
        "parameters": {"period": 10, "multiplier": 3.0},
        "description": "SuperTrend direction: 1 = bullish, −1 = bearish.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "value",
    },
    "ichimoku_tenkan": {
        "display_name": "Ichimoku Tenkan-sen",
        "category": "Baseline",
        "parameters": {"tenkan_period": 9},
        "description": "(Highest high + Lowest low) / 2 over tenkan_period — conversion line.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low"],
        "output_type": "line",
    },
    "ichimoku_kijun": {
        "display_name": "Ichimoku Kijun-sen",
        "category": "Baseline",
        "parameters": {"kijun_period": 26},
        "description": "(Highest high + Lowest low) / 2 over kijun_period — base line.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low"],
        "output_type": "line",
    },
    "ichimoku_span_a": {
        "display_name": "Ichimoku Senkou Span A",
        "category": "Baseline",
        "parameters": {"tenkan_period": 9, "kijun_period": 26},
        "description": "(Tenkan + Kijun) / 2 — leading span A.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low"],
        "output_type": "line",
    },
    "ichimoku_span_b": {
        "display_name": "Ichimoku Senkou Span B",
        "category": "Baseline",
        "parameters": {"senkou_b_period": 52},
        "description": "(Highest high + Lowest low) / 2 over senkou_b_period — leading span B.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low"],
        "output_type": "line",
    },
    "ichimoku_chikou": {
        "display_name": "Ichimoku Chikou Span",
        "category": "Baseline",
        "parameters": {"chikou_offset": 26},
        "description": "Close shifted back chikou_offset bars — lagging span.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "adx_value": {
        "display_name": "ADX Value",
        "category": "Baseline",
        "parameters": {"period": 14},
        "description": "Average Directional Index — measures trend strength (0–100).",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "plus_di": {
        "display_name": "+DI",
        "category": "Baseline",
        "parameters": {"period": 14},
        "description": "Positive Directional Indicator.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "minus_di": {
        "display_name": "-DI",
        "category": "Baseline",
        "parameters": {"period": 14},
        "description": "Negative Directional Indicator.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },

    # ===== RISK / POSITION FILTERS (91-100) ================================

    "psar": {
        "display_name": "Parabolic SAR",
        "category": "Risk",
        "parameters": {"af_start": 0.02, "af_step": 0.02, "af_max": 0.2},
        "description": "Parabolic Stop and Reverse trailing stop line.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "psar_direction": {
        "display_name": "Parabolic SAR Direction",
        "category": "Risk",
        "parameters": {"af_start": 0.02, "af_step": 0.02, "af_max": 0.2},
        "description": "Parabolic SAR direction: 1 = bullish, −1 = bearish.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "value",
    },
    "max_drawdown_n": {
        "display_name": "Max Drawdown over N bars",
        "category": "Risk",
        "parameters": {"period": 20},
        "description": "Maximum percentage drawdown from peak over the last *period* bars.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "volatility_rank": {
        "display_name": "Volatility Rank",
        "category": "Risk",
        "parameters": {"short_period": 20, "long_period": 252},
        "description": "Percentile rank of current short-period volatility over the long lookback.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "atr_stop": {
        "display_name": "ATR-based Stop",
        "category": "Risk",
        "parameters": {"period": 14, "multiplier": 2.0},
        "description": "Close − multiplier × ATR — dynamic stop-loss level.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "line",
    },
    "trailing_high": {
        "display_name": "Trailing N-bar High",
        "category": "Risk",
        "parameters": {"period": 20},
        "description": "Rolling max of close — trailing stop reference for longs.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "trailing_low": {
        "display_name": "Trailing N-bar Low",
        "category": "Risk",
        "parameters": {"period": 20},
        "description": "Rolling min of close — trailing stop reference for shorts.",
        "supported_operators": _NUMERIC_OPS,
        "required_fields": ["close"],
        "output_type": "line",
    },
    "volume_spike": {
        "display_name": "Volume Spike",
        "category": "Risk",
        "parameters": {"period": 20, "threshold": 2.0},
        "description": "True when volume > threshold × SMA(volume) — detects unusual activity.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["volume"],
        "output_type": "boolean",
    },
    "price_above_ma": {
        "display_name": "Price Above MA Filter",
        "category": "Risk",
        "parameters": {"period": 200, "ma_type": "sma"},
        "description": "Boolean: True when close > MA(period).",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["close"],
        "output_type": "boolean",
    },
    "adx_filter": {
        "display_name": "ADX Filter",
        "category": "Risk",
        "parameters": {"period": 14, "threshold": 25},
        "description": "Boolean: True when ADX > threshold — trending-market filter.",
        "supported_operators": _BOOL_OPS,
        "required_fields": ["high", "low", "close"],
        "output_type": "boolean",
    },
}

# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------

CATEGORIES = sorted({v["category"] for v in INDICATOR_CATALOG.values()})


def get_indicator_meta(key: str) -> dict | None:
    """Return metadata dict for *key*, or None if not found."""
    return INDICATOR_CATALOG.get(key)


def list_by_category(category: str) -> list[str]:
    """Return all indicator keys belonging to *category*."""
    return [k for k, v in INDICATOR_CATALOG.items() if v["category"] == category]


def search_indicators(query: str) -> list[str]:
    """Simple substring search across key and display_name."""
    q = query.lower()
    return [
        k for k, v in INDICATOR_CATALOG.items()
        if q in k or q in v["display_name"].lower() or q in v["description"].lower()
    ]
